# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: labs
spec:
  owner: "group:default/mcmuralishclint"
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-clean-code
  description: scaffolded go project
  links:
    - url: https://dashboard.example.com
      title: Admin Setting
      icon: dashboard
  annotations:
    github.com/project-slug: mcmuralishclint/my-go-app
    github.com/actions-workflow: https://github.com/mcmuralishclint/my-go-app/actions
    backstage.io/kubernetes-id: go-clean-code
    circleci.com/project-slug: github/mcmuralishclint/my-go-app
    kibana-url: "https://elksecond.chickenkiller.com:5601/app/dashboards#/view/edf84fe0-e1a0-11e7-b6d5-4dc382ef7f5b?_g=()&_a=()"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
    prometheus.io/alert: "all"
    pagerduty.com/integration-key: 4c280fa2a1094100d0767478390a85d6
    pulumi.com/project-slug: mcmuralishclint/pulumi-cicd/dev
    pulumi.com/orga-slug: mcmuralishclint
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/mcmuralishclint"
  system: marketplace
