steps:
  # Step 1: Pull the base image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', '-docker.pkg.dev/project/folder/:latest']

  # Step 2: Build the application image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '-docker.pkg.dev/project/folder/:latest',
      '--cache-from', '-docker.pkg.dev/project/folder/:latest',
      '.'
    ]

  # # Step 3: Run tests
  # - name: 'gcr.io//$REPO_NAME:latest'
  #   entrypoint: 'sh'
  #   args: ['-c', 'your-test-command-here']

  # Step 4: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '-docker.pkg.dev/project/folder/:latest']

  # Step 4: Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - cloudrun
      - "--image"
      - "-docker.pkg.dev/project/folder/:latest"
      - "--platform"
      - "managed"
      - "--region"
      - ""
      - "--allow-unauthenticated"
      - "--port"
      - "8008"

# Images to be pushed to Container Registry
images:
  - '-docker.pkg.dev/project/folder/:latest'

# Timeout for the entire build process
timeout: '1800s'